# Generated by Django 5.2.4 on 2026-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resubmission', 'Resubmission Requested')], default='pending', max_length=30),
        ),
    ]
